GET http://localhost:3000/products

###
GET http://localhost:3000/product/recommended

###
GET http://localhost:3000/product/get/clv2ktl8b0000g1kr9zoqjjl7

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "title": "HQ Nº1 Amazing Spiderman",
  "description": "Spiderman version Nº 1",
  "thumb": "https://http2.mlstatic.com/D_NQ_NP_757460-MLB50284638311_062022-O.webp",
  "price": 69.93
}

###
GET http://localhost:3001/orders

###
GET http://localhost:3001/order/cluhiumdc00004fmn947yft4r

###
POST http://localhost:3001/orders
Content-Type: application/json

{
  "price": 69.93,
  "quantity": 2,
  "product_id": "clvue8q6l0000kgyi81ujmjgv"
}

###
GET http://localhost:3003/clvue8q6l0000kgyi81ujmjgv

###
POST http://localhost:3003
Content-Type: application/json

{
  "title": "Teste",
  "content": "lorem",
  "userId": "clvue8q6l0000kgyi81ujmjgv"
}
