GET http://localhost:3000/products

###
GET http://localhost:3000/products/clua0b9ni0000sz8er2oonbq3

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "title": "HQ Nº1 Amazing Spiderman",
  "description": "Spiderman version Nº 1",
  "thumb": "https://http2.mlstatic.com/D_NQ_NP_757460-MLB50284638311_062022-O.webp",
  "price": 69.93
}

###
GET http://localhost:3001/order/cluhiumdc00004fmn947yft4r

###
POST http://localhost:3001/orders
Content-Type: application/json

{
  "price": 69.93,
  "quantity": 2,
  "product_id": "cluh7n0gd0000wokpwp9oeixx"
}