@base_url=http://localhost:8080

###
GET {{base_url}}/products

###
GET {{base_url}}/product/recommended

###
GET {{base_url}}/product/get/clv2ktl8b0000g1kr9zoqjjl7

###
POST {{base_url}}/products
Content-Type: application/json

{
  "title": "HQ Nº1 Amazing Spiderman",
  "description": "Spiderman version Nº 1",
  "thumb": "https://http2.mlstatic.com/D_NQ_NP_757460-MLB50284638311_062022-O.webp",
  "price": 69.93
}

###
GET {{base_url}}/orders

###
GET {{base_url}}/order/clvzp8xoz000010cfcfuuxwho

###
POST {{base_url}}/orders
Content-Type: application/json

{
  "price": 69.93,
  "quantity": 2,
  "product_id": "clvue8q6l0000kgyi81ujmjgv"
}

###
GET {{base_url}}/notifications
Content-Type: application/json

{
  "userId": "clvue8q6l0000kgyi81ujmjgv"
}

###
PATCH {{base_url}}/notifications
Content-Type: application/json

{
  "userId": "clvue8q6l0000kgyi81ujmjgv",
  "notificationId": "clvue8q6l0000kgyi81ujmjgv"
}