services:
  # Microservices #

  products:
    build:
      dockerfile: ./.docker/bin/products/Dockerfile
      context: .
    container_name: "mercado_dev-app--products"
    entrypoint: ./start.sh
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/products
    depends_on:
      - mysql
    ports:
      - 3000:3000
      
  orders:
    build:
      dockerfile: ./.docker/bin/orders/Dockerfile
      context: .
    container_name: "mercado_dev-app--orders"
    entrypoint: ./start.sh
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/orders
    depends_on:
      - mysql
      - kafka
    ports:
      - 3001:3001

  payments:
    build:
      dockerfile: ./.docker/bin/payments/Dockerfile
      context: .
    container_name: "mercado_dev-app--payments"
    entrypoint: ./start.sh
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/payments
    depends_on:
      - mysql
      - kafka
    ports:
      - 3002:3002

  ######################

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: "mercado_dev-zookeeper"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:7.3.0
    hostname: kafka
    container_name: "mercado_dev-kafka"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  # control-center:
  #   image: confluentinc/cp-enterprise-control-center:7.3.0
  #   hostname: control-center
  #   container_name: "mercado_dev-controlcenter"
  #   depends_on:
  #     - kafka
  #   ports:
  #     - "9021:9021"
  #   environment:
  #     CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
  #     CONTROL_CENTER_REPLICATION_FACTOR: 1
  #     CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
  #     CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
  #     CONFLUENT_METRICS_TOPIC_REPLICATION: 1
  #     PORT: 9021
  
  mysql:
    image: mysql:8.0.30-debian
    container_name: "mercado_dev-db"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d